//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 09:06:29 PM EST 
//

import org.jvnet.jaxb2_commons.xml.bind.ContextPathAware;

public class RoundtripTest
    extends org.jvnet.hyperjaxb3.ejb.test.RoundtripTest
    implements ContextPathAware
{


    public String getContextPath() {
        return "com.basu.schemas";
    }

    public String getPersistenceUnitName() {
        return "com.basu.schemas";
    }

}
