//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.18 at 12:05:13 PM EST 
//


package com.basu.schemas;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


@Entity(name = "OrderItem")
@Table(name = "ORDERITEM")
@Inheritance(strategy = InheritanceType.JOINED)
public class OrderItem
    implements Serializable, Equals, HashCode
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected SalesOrder order;
    protected String orderItemName;
    protected double orderItemFinalPrice;
    protected int orderQuantity;
    protected long id;
    protected Product product;

    
    @OneToOne(targetEntity=Product.class, fetch=FetchType.LAZY)
    @JoinColumn(name="ORDERITEM_PRODUCT_ID")
	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	/**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Order }
     *     
     */
    @ManyToOne(targetEntity = SalesOrder.class)
    public SalesOrder getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Order }
     *     
     */
    public void setOrder(SalesOrder value) {
        this.order = value;
    }

    @Transient
    public boolean isSetOrder() {
        return (this.order!= null);
    }

    /**
     * Gets the value of the orderItemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ORDERITEMNAME", length = 255)
    public String getOrderItemName() {
        return orderItemName;
    }

    /**
     * Sets the value of the orderItemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderItemName(String value) {
        this.orderItemName = value;
    }

    @Transient
    public boolean isSetOrderItemName() {
        return (this.orderItemName!= null);
    }

    /**
     * Gets the value of the orderItemFinalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "ORDERITEMFINALPRICE", precision = 20, scale = 10)
    public double getOrderItemFinalPrice() {
        return orderItemFinalPrice;
    }

    /**
     * Sets the value of the orderItemFinalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOrderItemFinalPrice(double value) {
        this.orderItemFinalPrice = value;
    }


    /**
     * Gets the value of the orderQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "ORDERQUANTITY", precision = 20, scale = 0)
    public int getOrderQuantity() {
        return orderQuantity;
    }

    /**
     * Sets the value of the orderQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderQuantity(int value) {
        this.orderQuantity = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "ID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(long value) {
        this.id = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof OrderItem)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final OrderItem that = ((OrderItem) object);
        {
            SalesOrder lhsOrder;
            lhsOrder = this.getOrder();
            SalesOrder rhsOrder;
            rhsOrder = that.getOrder();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "order", lhsOrder), LocatorUtils.property(thatLocator, "order", rhsOrder), lhsOrder, rhsOrder)) {
                return false;
            }
        }
        {
            String lhsOrderItemName;
            lhsOrderItemName = this.getOrderItemName();
            String rhsOrderItemName;
            rhsOrderItemName = that.getOrderItemName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderItemName", lhsOrderItemName), LocatorUtils.property(thatLocator, "orderItemName", rhsOrderItemName), lhsOrderItemName, rhsOrderItemName)) {
                return false;
            }
        }
        {
            double lhsOrderItemFinalPrice;
            lhsOrderItemFinalPrice = this.getOrderItemFinalPrice();
            double rhsOrderItemFinalPrice;
            rhsOrderItemFinalPrice = that.getOrderItemFinalPrice();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderItemFinalPrice", lhsOrderItemFinalPrice), LocatorUtils.property(thatLocator, "orderItemFinalPrice", rhsOrderItemFinalPrice), lhsOrderItemFinalPrice, rhsOrderItemFinalPrice)) {
                return false;
            }
        }
        {
            int lhsOrderQuantity;
            lhsOrderQuantity = this.getOrderQuantity();
            int rhsOrderQuantity;
            rhsOrderQuantity = that.getOrderQuantity();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderQuantity", lhsOrderQuantity), LocatorUtils.property(thatLocator, "orderQuantity", rhsOrderQuantity), lhsOrderQuantity, rhsOrderQuantity)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            SalesOrder theOrder;
            theOrder = this.getOrder();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "order", theOrder), currentHashCode, theOrder);
        }
        {
            String theOrderItemName;
            theOrderItemName = this.getOrderItemName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderItemName", theOrderItemName), currentHashCode, theOrderItemName);
        }
        {
            double theOrderItemFinalPrice;
            theOrderItemFinalPrice = this.getOrderItemFinalPrice();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderItemFinalPrice", theOrderItemFinalPrice), currentHashCode, theOrderItemFinalPrice);
        }
        {
            int theOrderQuantity;
            theOrderQuantity = this.getOrderQuantity();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderQuantity", theOrderQuantity), currentHashCode, theOrderQuantity);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
