//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.18 at 12:05:13 PM EST 
//


package com.basu.schemas;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDate;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for Order complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Order">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="OrderShipName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderShipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderShipAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderZip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderFax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderShipping" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="OrderTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="OrderEmail" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="OrderShipped" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="OrderTrackingNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderList" type="{xmlapi_1.0}OrderItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="User" type="{xmlapi_1.0}User"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Order", propOrder = {
    "orderAmount",
    "orderShipName",
    "orderShipAddress",
    "orderShipAddress2",
    "orderCity",
    "orderState",
    "orderZip",
    "orderCountry",
    "orderPhone",
    "orderFax",
    "orderShipping",
    "orderTax",
    "orderEmail",
    "orderDate",
    "orderShipped",
    "orderTrackingNumber",
    "orderList",
    "user"
})
@Entity(name = "Order")
@Table(name = "ORDER_")
@Inheritance(strategy = InheritanceType.JOINED)
public class Order
    implements Serializable, Equals, HashCode
{

    @XmlElement(name = "OrderAmount", required = true)
    protected BigDecimal orderAmount;
    @XmlElement(name = "OrderShipName", required = true)
    protected String orderShipName;
    @XmlElement(name = "OrderShipAddress", required = true)
    protected String orderShipAddress;
    @XmlElement(name = "OrderShipAddress2", required = true)
    protected String orderShipAddress2;
    @XmlElement(name = "OrderCity", required = true)
    protected String orderCity;
    @XmlElement(name = "OrderState", required = true)
    protected String orderState;
    @XmlElement(name = "OrderZip", required = true)
    protected String orderZip;
    @XmlElement(name = "OrderCountry", required = true)
    protected String orderCountry;
    @XmlElement(name = "OrderPhone", required = true)
    protected String orderPhone;
    @XmlElement(name = "OrderFax", required = true)
    protected String orderFax;
    @XmlElement(name = "OrderShipping", required = true)
    protected BigDecimal orderShipping;
    @XmlElement(name = "OrderTax", required = true)
    protected BigDecimal orderTax;
    @XmlElement(name = "OrderEmail", required = true)
    protected BigDecimal orderEmail;
    @XmlElement(name = "OrderDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar orderDate;
    @XmlElement(name = "OrderShipped")
    protected boolean orderShipped;
    @XmlElement(name = "OrderTrackingNumber", required = true)
    protected String orderTrackingNumber;
    @XmlElement(name = "OrderList")
    protected List<OrderItem> orderList;
    @XmlElement(name = "User", required = true)
    protected User user;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the orderAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "ORDERAMOUNT", precision = 20, scale = 10)
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * Sets the value of the orderAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOrderAmount(BigDecimal value) {
        this.orderAmount = value;
    }

    @Transient
    public boolean isSetOrderAmount() {
        return (this.orderAmount!= null);
    }

    /**
     * Gets the value of the orderShipName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ORDERSHIPNAME", length = 255)
    public String getOrderShipName() {
        return orderShipName;
    }

    /**
     * Sets the value of the orderShipName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderShipName(String value) {
        this.orderShipName = value;
    }

    @Transient
    public boolean isSetOrderShipName() {
        return (this.orderShipName!= null);
    }

    /**
     * Gets the value of the orderShipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ORDERSHIPADDRESS", length = 255)
    public String getOrderShipAddress() {
        return orderShipAddress;
    }

    /**
     * Sets the value of the orderShipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderShipAddress(String value) {
        this.orderShipAddress = value;
    }

    @Transient
    public boolean isSetOrderShipAddress() {
        return (this.orderShipAddress!= null);
    }

    /**
     * Gets the value of the orderShipAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ORDERSHIPADDRESS2", length = 255)
    public String getOrderShipAddress2() {
        return orderShipAddress2;
    }

    /**
     * Sets the value of the orderShipAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderShipAddress2(String value) {
        this.orderShipAddress2 = value;
    }

    @Transient
    public boolean isSetOrderShipAddress2() {
        return (this.orderShipAddress2 != null);
    }

    /**
     * Gets the value of the orderCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ORDERCITY", length = 255)
    public String getOrderCity() {
        return orderCity;
    }

    /**
     * Sets the value of the orderCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderCity(String value) {
        this.orderCity = value;
    }

    @Transient
    public boolean isSetOrderCity() {
        return (this.orderCity!= null);
    }

    /**
     * Gets the value of the orderState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ORDERSTATE", length = 255)
    public String getOrderState() {
        return orderState;
    }

    /**
     * Sets the value of the orderState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderState(String value) {
        this.orderState = value;
    }

    @Transient
    public boolean isSetOrderState() {
        return (this.orderState!= null);
    }

    /**
     * Gets the value of the orderZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ORDERZIP", length = 255)
    public String getOrderZip() {
        return orderZip;
    }

    /**
     * Sets the value of the orderZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderZip(String value) {
        this.orderZip = value;
    }

    @Transient
    public boolean isSetOrderZip() {
        return (this.orderZip!= null);
    }

    /**
     * Gets the value of the orderCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ORDERCOUNTRY", length = 255)
    public String getOrderCountry() {
        return orderCountry;
    }

    /**
     * Sets the value of the orderCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderCountry(String value) {
        this.orderCountry = value;
    }

    @Transient
    public boolean isSetOrderCountry() {
        return (this.orderCountry!= null);
    }

    /**
     * Gets the value of the orderPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ORDERPHONE", length = 255)
    public String getOrderPhone() {
        return orderPhone;
    }

    /**
     * Sets the value of the orderPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderPhone(String value) {
        this.orderPhone = value;
    }

    @Transient
    public boolean isSetOrderPhone() {
        return (this.orderPhone!= null);
    }

    /**
     * Gets the value of the orderFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ORDERFAX", length = 255)
    public String getOrderFax() {
        return orderFax;
    }

    /**
     * Sets the value of the orderFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderFax(String value) {
        this.orderFax = value;
    }

    @Transient
    public boolean isSetOrderFax() {
        return (this.orderFax!= null);
    }

    /**
     * Gets the value of the orderShipping property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "ORDERSHIPPING", precision = 20, scale = 10)
    public BigDecimal getOrderShipping() {
        return orderShipping;
    }

    /**
     * Sets the value of the orderShipping property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOrderShipping(BigDecimal value) {
        this.orderShipping = value;
    }

    @Transient
    public boolean isSetOrderShipping() {
        return (this.orderShipping!= null);
    }

    /**
     * Gets the value of the orderTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "ORDERTAX", precision = 20, scale = 10)
    public BigDecimal getOrderTax() {
        return orderTax;
    }

    /**
     * Sets the value of the orderTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOrderTax(BigDecimal value) {
        this.orderTax = value;
    }

    @Transient
    public boolean isSetOrderTax() {
        return (this.orderTax!= null);
    }

    /**
     * Gets the value of the orderEmail property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "ORDEREMAIL", precision = 20, scale = 10)
    public BigDecimal getOrderEmail() {
        return orderEmail;
    }

    /**
     * Sets the value of the orderEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOrderEmail(BigDecimal value) {
        this.orderEmail = value;
    }

    @Transient
    public boolean isSetOrderEmail() {
        return (this.orderEmail!= null);
    }

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrderDate(XMLGregorianCalendar value) {
        this.orderDate = value;
    }

    @Transient
    public boolean isSetOrderDate() {
        return (this.orderDate!= null);
    }

    /**
     * Gets the value of the orderShipped property.
     * 
     */
    @Basic
    @Column(name = "ORDERSHIPPED")
    public boolean isOrderShipped() {
        return orderShipped;
    }

    /**
     * Sets the value of the orderShipped property.
     * 
     */
    public void setOrderShipped(boolean value) {
        this.orderShipped = value;
    }

    @Transient
    public boolean isSetOrderShipped() {
        return true;
    }

    /**
     * Gets the value of the orderTrackingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ORDERTRACKINGNUMBER", length = 255)
    public String getOrderTrackingNumber() {
        return orderTrackingNumber;
    }

    /**
     * Sets the value of the orderTrackingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderTrackingNumber(String value) {
        this.orderTrackingNumber = value;
    }

    @Transient
    public boolean isSetOrderTrackingNumber() {
        return (this.orderTrackingNumber!= null);
    }

    /**
     * Gets the value of the orderList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderItem }
     * 
     * 
     */
    @OneToMany(targetEntity = OrderItem.class, cascade = {
        CascadeType.ALL
    }, fetch = FetchType.LAZY)
    @JoinColumn(name = "ORDERLIST_ORDER__HJID")
    public List<OrderItem> getOrderList() {
        if (orderList == null) {
            orderList = new ArrayList<OrderItem>();
        }
        return this.orderList;
    }

    /**
     * 
     * 
     */
    public void setOrderList(List<OrderItem> orderList) {
        this.orderList = orderList;
    }

    @Transient
    public boolean isSetOrderList() {
        return ((this.orderList!= null)&&(!this.orderList.isEmpty()));
    }

    public void unsetOrderList() {
        this.orderList = null;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    @ManyToOne(targetEntity = User.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "USER__ORDER__HJID")
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    @Transient
    public boolean isSetUser() {
        return (this.user!= null);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @Basic
    @Column(name = "ORDERDATEITEM")
    @Temporal(TemporalType.DATE)
    public Date getOrderDateItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDate.class, this.getOrderDate());
    }

    public void setOrderDateItem(Date target) {
        setOrderDate(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDate.class, target));
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Order)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Order that = ((Order) object);
        {
            BigDecimal lhsOrderAmount;
            lhsOrderAmount = this.getOrderAmount();
            BigDecimal rhsOrderAmount;
            rhsOrderAmount = that.getOrderAmount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderAmount", lhsOrderAmount), LocatorUtils.property(thatLocator, "orderAmount", rhsOrderAmount), lhsOrderAmount, rhsOrderAmount)) {
                return false;
            }
        }
        {
            String lhsOrderShipName;
            lhsOrderShipName = this.getOrderShipName();
            String rhsOrderShipName;
            rhsOrderShipName = that.getOrderShipName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderShipName", lhsOrderShipName), LocatorUtils.property(thatLocator, "orderShipName", rhsOrderShipName), lhsOrderShipName, rhsOrderShipName)) {
                return false;
            }
        }
        {
            String lhsOrderShipAddress;
            lhsOrderShipAddress = this.getOrderShipAddress();
            String rhsOrderShipAddress;
            rhsOrderShipAddress = that.getOrderShipAddress();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderShipAddress", lhsOrderShipAddress), LocatorUtils.property(thatLocator, "orderShipAddress", rhsOrderShipAddress), lhsOrderShipAddress, rhsOrderShipAddress)) {
                return false;
            }
        }
        {
            String lhsOrderShipAddress2;
            lhsOrderShipAddress2 = this.getOrderShipAddress2();
            String rhsOrderShipAddress2;
            rhsOrderShipAddress2 = that.getOrderShipAddress2();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderShipAddress2", lhsOrderShipAddress2), LocatorUtils.property(thatLocator, "orderShipAddress2", rhsOrderShipAddress2), lhsOrderShipAddress2, rhsOrderShipAddress2)) {
                return false;
            }
        }
        {
            String lhsOrderCity;
            lhsOrderCity = this.getOrderCity();
            String rhsOrderCity;
            rhsOrderCity = that.getOrderCity();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderCity", lhsOrderCity), LocatorUtils.property(thatLocator, "orderCity", rhsOrderCity), lhsOrderCity, rhsOrderCity)) {
                return false;
            }
        }
        {
            String lhsOrderState;
            lhsOrderState = this.getOrderState();
            String rhsOrderState;
            rhsOrderState = that.getOrderState();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderState", lhsOrderState), LocatorUtils.property(thatLocator, "orderState", rhsOrderState), lhsOrderState, rhsOrderState)) {
                return false;
            }
        }
        {
            String lhsOrderZip;
            lhsOrderZip = this.getOrderZip();
            String rhsOrderZip;
            rhsOrderZip = that.getOrderZip();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderZip", lhsOrderZip), LocatorUtils.property(thatLocator, "orderZip", rhsOrderZip), lhsOrderZip, rhsOrderZip)) {
                return false;
            }
        }
        {
            String lhsOrderCountry;
            lhsOrderCountry = this.getOrderCountry();
            String rhsOrderCountry;
            rhsOrderCountry = that.getOrderCountry();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderCountry", lhsOrderCountry), LocatorUtils.property(thatLocator, "orderCountry", rhsOrderCountry), lhsOrderCountry, rhsOrderCountry)) {
                return false;
            }
        }
        {
            String lhsOrderPhone;
            lhsOrderPhone = this.getOrderPhone();
            String rhsOrderPhone;
            rhsOrderPhone = that.getOrderPhone();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderPhone", lhsOrderPhone), LocatorUtils.property(thatLocator, "orderPhone", rhsOrderPhone), lhsOrderPhone, rhsOrderPhone)) {
                return false;
            }
        }
        {
            String lhsOrderFax;
            lhsOrderFax = this.getOrderFax();
            String rhsOrderFax;
            rhsOrderFax = that.getOrderFax();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderFax", lhsOrderFax), LocatorUtils.property(thatLocator, "orderFax", rhsOrderFax), lhsOrderFax, rhsOrderFax)) {
                return false;
            }
        }
        {
            BigDecimal lhsOrderShipping;
            lhsOrderShipping = this.getOrderShipping();
            BigDecimal rhsOrderShipping;
            rhsOrderShipping = that.getOrderShipping();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderShipping", lhsOrderShipping), LocatorUtils.property(thatLocator, "orderShipping", rhsOrderShipping), lhsOrderShipping, rhsOrderShipping)) {
                return false;
            }
        }
        {
            BigDecimal lhsOrderTax;
            lhsOrderTax = this.getOrderTax();
            BigDecimal rhsOrderTax;
            rhsOrderTax = that.getOrderTax();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderTax", lhsOrderTax), LocatorUtils.property(thatLocator, "orderTax", rhsOrderTax), lhsOrderTax, rhsOrderTax)) {
                return false;
            }
        }
        {
            BigDecimal lhsOrderEmail;
            lhsOrderEmail = this.getOrderEmail();
            BigDecimal rhsOrderEmail;
            rhsOrderEmail = that.getOrderEmail();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderEmail", lhsOrderEmail), LocatorUtils.property(thatLocator, "orderEmail", rhsOrderEmail), lhsOrderEmail, rhsOrderEmail)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsOrderDate;
            lhsOrderDate = this.getOrderDate();
            XMLGregorianCalendar rhsOrderDate;
            rhsOrderDate = that.getOrderDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderDate", lhsOrderDate), LocatorUtils.property(thatLocator, "orderDate", rhsOrderDate), lhsOrderDate, rhsOrderDate)) {
                return false;
            }
        }
        {
            boolean lhsOrderShipped;
            lhsOrderShipped = (this.isSetOrderShipped()?this.isOrderShipped():false);
            boolean rhsOrderShipped;
            rhsOrderShipped = (that.isSetOrderShipped()?that.isOrderShipped():false);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderShipped", lhsOrderShipped), LocatorUtils.property(thatLocator, "orderShipped", rhsOrderShipped), lhsOrderShipped, rhsOrderShipped)) {
                return false;
            }
        }
        {
            String lhsOrderTrackingNumber;
            lhsOrderTrackingNumber = this.getOrderTrackingNumber();
            String rhsOrderTrackingNumber;
            rhsOrderTrackingNumber = that.getOrderTrackingNumber();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderTrackingNumber", lhsOrderTrackingNumber), LocatorUtils.property(thatLocator, "orderTrackingNumber", rhsOrderTrackingNumber), lhsOrderTrackingNumber, rhsOrderTrackingNumber)) {
                return false;
            }
        }
        {
            List<OrderItem> lhsOrderList;
            lhsOrderList = (this.isSetOrderList()?this.getOrderList():null);
            List<OrderItem> rhsOrderList;
            rhsOrderList = (that.isSetOrderList()?that.getOrderList():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orderList", lhsOrderList), LocatorUtils.property(thatLocator, "orderList", rhsOrderList), lhsOrderList, rhsOrderList)) {
                return false;
            }
        }
        {
            User lhsUser;
            lhsUser = this.getUser();
            User rhsUser;
            rhsUser = that.getUser();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "user", lhsUser), LocatorUtils.property(thatLocator, "user", rhsUser), lhsUser, rhsUser)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            BigDecimal theOrderAmount;
            theOrderAmount = this.getOrderAmount();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderAmount", theOrderAmount), currentHashCode, theOrderAmount);
        }
        {
            String theOrderShipName;
            theOrderShipName = this.getOrderShipName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderShipName", theOrderShipName), currentHashCode, theOrderShipName);
        }
        {
            String theOrderShipAddress;
            theOrderShipAddress = this.getOrderShipAddress();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderShipAddress", theOrderShipAddress), currentHashCode, theOrderShipAddress);
        }
        {
            String theOrderShipAddress2;
            theOrderShipAddress2 = this.getOrderShipAddress2();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderShipAddress2", theOrderShipAddress2), currentHashCode, theOrderShipAddress2);
        }
        {
            String theOrderCity;
            theOrderCity = this.getOrderCity();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderCity", theOrderCity), currentHashCode, theOrderCity);
        }
        {
            String theOrderState;
            theOrderState = this.getOrderState();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderState", theOrderState), currentHashCode, theOrderState);
        }
        {
            String theOrderZip;
            theOrderZip = this.getOrderZip();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderZip", theOrderZip), currentHashCode, theOrderZip);
        }
        {
            String theOrderCountry;
            theOrderCountry = this.getOrderCountry();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderCountry", theOrderCountry), currentHashCode, theOrderCountry);
        }
        {
            String theOrderPhone;
            theOrderPhone = this.getOrderPhone();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderPhone", theOrderPhone), currentHashCode, theOrderPhone);
        }
        {
            String theOrderFax;
            theOrderFax = this.getOrderFax();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderFax", theOrderFax), currentHashCode, theOrderFax);
        }
        {
            BigDecimal theOrderShipping;
            theOrderShipping = this.getOrderShipping();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderShipping", theOrderShipping), currentHashCode, theOrderShipping);
        }
        {
            BigDecimal theOrderTax;
            theOrderTax = this.getOrderTax();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderTax", theOrderTax), currentHashCode, theOrderTax);
        }
        {
            BigDecimal theOrderEmail;
            theOrderEmail = this.getOrderEmail();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderEmail", theOrderEmail), currentHashCode, theOrderEmail);
        }
        {
            XMLGregorianCalendar theOrderDate;
            theOrderDate = this.getOrderDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderDate", theOrderDate), currentHashCode, theOrderDate);
        }
        {
            boolean theOrderShipped;
            theOrderShipped = (this.isSetOrderShipped()?this.isOrderShipped():false);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderShipped", theOrderShipped), currentHashCode, theOrderShipped);
        }
        {
            String theOrderTrackingNumber;
            theOrderTrackingNumber = this.getOrderTrackingNumber();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderTrackingNumber", theOrderTrackingNumber), currentHashCode, theOrderTrackingNumber);
        }
        {
            List<OrderItem> theOrderList;
            theOrderList = (this.isSetOrderList()?this.getOrderList():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orderList", theOrderList), currentHashCode, theOrderList);
        }
        {
            User theUser;
            theUser = this.getUser();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "user", theUser), currentHashCode, theUser);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
