//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.18 at 12:05:13 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "xmlapi_1.0")
package com.basu.schemas;
