//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.18 at 12:05:13 PM EST 
//


package com.basu.schemas;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDate;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;

@Entity(name = "Product")
@Table(name = "PRODUCT")
@Inheritance(strategy = InheritanceType.JOINED)
public class Product
    implements Serializable
{
	
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected String productSKU;
    protected String productName;
    protected BigDecimal productPrice;
    protected BigDecimal productWeight;
    protected String productShortDesc;
    protected String productLongDesc;
    protected XMLGregorianCalendar productUpdateDate;
    protected BigInteger productStock;
    protected ProductCategory productCategory;
    protected Long hjid;
    protected Image mainImage;
    protected Set<Image> additionalImages;
    protected ProductDimensions productDimensions;
    protected Set<Attributes> attributes;
    protected boolean featuredProduct=false;
    protected Set<OrderItem> orderItems;
    
    
    
    
    
    @OneToOne(targetEntity=OrderItem.class, fetch=FetchType.LAZY)
    @JoinColumn(name="ORDERITEM_PRODUCT_ID")
    public Set<OrderItem> getOrderItems() {
		return orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Basic
    @Column(name="FEATUREDPRODUCT" )
    public boolean isFeaturedProduct() {
		return featuredProduct;
	}

	public void setFeaturedProduct(boolean featuredProduct) {
		this.featuredProduct = featuredProduct;
	}

	@OneToMany(orphanRemoval = true, fetch=FetchType.EAGER, targetEntity = Attributes.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name="ATTRIBUTE_PRODUCT_ID")
	@OrderColumn
    public Set<Attributes> getAttributes() {
		return attributes;
	}

	public void setAttributes(Set<Attributes> attributes) {
		this.attributes = attributes;
	}

	@OneToOne(fetch=FetchType.EAGER, cascade=CascadeType.ALL)
    @JoinColumn(name="PRODUCT_DIMENSION_ID")
    public ProductDimensions getProductDimensions() {
		return productDimensions;
	}

	public void setProductDimensions(ProductDimensions productDimensions) {
		this.productDimensions = productDimensions;
	}

	@OneToOne(fetch=FetchType.EAGER, cascade= CascadeType.ALL)
    @JoinColumn(name="PRODUCT_MAINIMAGE_ID")
    public Image getMainImage() {
		return mainImage;
	}

	public void setMainImage(Image mainImage) {
		this.mainImage = mainImage;
	}

    @OneToMany(orphanRemoval = true, fetch=FetchType.EAGER, targetEntity = Image.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ADDITIONALIMAGE_PRODUCT_ID")
    @OrderColumn
	public Set<Image> getAdditionalImages() {
		return additionalImages;
	}

	public void setAdditionalImages(Set<Image> additionalImages) {
		this.additionalImages = additionalImages;
	}


	/**
     * Gets the value of the productSKU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PRODUCTSKU", length = 255)
    public String getProductSKU() {
        return productSKU;
    }

    /**
     * Sets the value of the productSKU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductSKU(String value) {
        this.productSKU = value;
    }

    @Transient
    public boolean isSetProductSKU() {
        return (this.productSKU!= null);
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PRODUCTNAME", length = 255)
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    @Transient
    public boolean isSetProductName() {
        return (this.productName!= null);
    }

    /**
     * Gets the value of the productPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "PRODUCTPRICE", precision = 20, scale = 10)
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * Sets the value of the productPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProductPrice(BigDecimal value) {
        this.productPrice = value;
    }

    @Transient
    public boolean isSetProductPrice() {
        return (this.productPrice!= null);
    }

    /**
     * Gets the value of the productWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "PRODUCTWEIGHT", precision = 20, scale = 10)
    public BigDecimal getProductWeight() {
        return productWeight;
    }

    /**
     * Sets the value of the productWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProductWeight(BigDecimal value) {
        this.productWeight = value;
    }

    @Transient
    public boolean isSetProductWeight() {
        return (this.productWeight!= null);
    }

    /**
     * Gets the value of the productShortDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PRODUCTSHORTDESC", length = 255)
    public String getProductShortDesc() {
        return productShortDesc;
    }

    /**
     * Sets the value of the productShortDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductShortDesc(String value) {
        this.productShortDesc = value;
    }

    @Transient
    public boolean isSetProductShortDesc() {
        return (this.productShortDesc!= null);
    }

    /**
     * Gets the value of the productLongDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PRODUCTLONGDESC", length = 65536)
    public String getProductLongDesc() {
        return productLongDesc;
    }

    /**
     * Sets the value of the productLongDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductLongDesc(String value) {
        this.productLongDesc = value;
    }

    @Transient
    public boolean isSetProductLongDesc() {
        return (this.productLongDesc!= null);
    }

    /**
     * Gets the value of the productUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getProductUpdateDate() {
        return productUpdateDate;
    }

    /**
     * Sets the value of the productUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProductUpdateDate(XMLGregorianCalendar value) {
        this.productUpdateDate = value;
    }

    @Transient
    public boolean isSetProductUpdateDate() {
        return (this.productUpdateDate!= null);
    }

    /**
     * Gets the value of the productStock property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "PRODUCTSTOCK", precision = 20, scale = 0)
    public BigInteger getProductStock() {
        return productStock;
    }

    /**
     * Sets the value of the productStock property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProductStock(BigInteger value) {
        this.productStock = value;
    }

    @Transient
    public boolean isSetProductStock() {
        return (this.productStock!= null);
    }

    /**
     * Gets the value of the productCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCategory }
     *     
     */
    @ManyToOne(targetEntity = ProductCategory.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PRODUCT_PRODUCTCATEGORY_ID")
    public ProductCategory getProductCategory() {
        return productCategory;
    }

    /**
     * Sets the value of the productCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCategory }
     *     
     */
    public void setProductCategory(ProductCategory value) {
        this.productCategory = value;
    }

    @Transient
    public boolean isSetProductCategory() {
        return (this.productCategory!= null);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @Basic
    @Column(name = "PRODUCTUPDATEDATEITEM")
    @Temporal(TemporalType.DATE)
    public Date getProductUpdateDateItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDate.class, this.getProductUpdateDate());
    }

    public void setProductUpdateDateItem(Date target) {
        setProductUpdateDate(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDate.class, target));
    }
}
